services:
  db:
    image: postgres:latest
    env_file: .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", $POSTGRES_DB, "-U", $POSTGRES_USER]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"
    restart: always
  migrate:
    image: migrate/migrate
    env_file: .env
    volumes:
      - internal/database/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DB", "up"]
    depends_on:
      db:
        condition: service_healthy
  app:
    build:
      context: .
      dockerfile: rss_aggregator.dockerfile
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
